---
- name: Install ipmitools
  become: True
  apt:
    name: ipmitool
    state: present
    update_cache: yes
    cache_valid_time: 1800

- name: Load kernel modules on boot
  become: True
  template:
    src: etc_modules-load.d_ipmi.conf.j2
    dest: /etc/modules-load.d/ipmi.conf
    owner: root
    group: root
    mode: 0644

- name: Ensure kernel modules are loaded
  become: True
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
   - ipmi_si
   - ipmi_devintf
   - ipmi_poweroff

- name: Configure IPMI IP
  become: True
  when: ipmiconfig is defined
  ipmi_lan:
    channel: "{{ ipmiconfig.lan.channel }}"
    config:
      ip: "{{ ipmiconfig.lan.ip }}"
      netmask: "{{ ipmiconfig.lan.netmask }}"
      gateway: "{{ ipmiconfig.lan.gateway }}"

- name: Configure IPMI users
  become: True
  when: ipmiconfig is defined
  ipmi_user:
    user: "{{ item.name }}"
    password: "{{ item.password }}"
    state: present
    privileges: "{{ item.privileges }}"
    channel: "{{ item.channel }}"
  with_items: "{{ ipmiconfig.users }}"
  no_log: True

- import_tasks: sol.yml
