---
- name: Update grub
  become: true
  ansible.builtin.command: update-grub
  changed_when: false

- name: Restart manual serial
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
  notify: Restart manual serial 2

- name: Restart manual serial 2
  become: true
  ansible.builtin.service:
    name: seria-getty@{{ sol_port }}
    state: restarted
